### PR TITLE
use pytest-mpl for image comparison tests

### PR DESCRIPTION
**Pull request by jswhit**

### CODE REVIEW

**Comment by akrherz** [comment]
Wow @jswhit , that's awesome that you are using pytest-mpl!  Are there any questions / troubles you had about using it?

**Comment by jswhit** [comment]
nope it was pretty straightforward.  I don't have it enabled in the CI tests since the older version of eccodes in ubuntu-latest appears to cause some of the tests to fail.

**Comment by jswhit** [comment]
@akrherz could you try running the image comparison tests on your machine? (`cd test; pytest test*py --mpl --mpl-baseline-path=baseline_images`)

**Comment by akrherz** [comment]
> could you try running the image comparison tests on your machine?

I had four failures with values slightly over 20 on linux 64 bit rhel8 python3.8 

FAILED test_ndfd_conus.py::test_ndfd_conus
FAILED test_ndfd_pr.py::test_ndfd_pr
FAILED test_rotated_ll.py::test_rotated_ll
FAILED test_tigge.py::test_tigge

I am unsure what you are wishing to accomplish with these tests?  getting consistent results from cartopy+matplotlib over various versions is not much fun :)  These differences aren't a result of pygrib issues are they?

**Comment by jswhit** [comment]
those are the same failures I see in the CI.  what version of eccodes are you running?  Could you email me the pngs for the failed tests?

**Comment by akrherz** [comment]
result-failed-diff
result-failed-diff
result-failed-diff
result-failed-diff

There's a mechanism to have the github job upload the failed images as artifacts, I can PR that.  eccodes=2.19.1

**Comment by jswhit** [comment]
Thanks.  Not the eccodes version then. Looks like the gridlines are messed up on a couple of those.  What's with the black background though?

To answer your question, what I'm trying to get at is whether the gelocation of the grid is correct.  I could do that by saving the correct lat and lons in a file I suppose.

**Comment by akrherz** [comment]
The files I attached are the `diff` images, which shows how the baseline image differs from the test result.  black means no difference at that pixel.  Can't you just test the `latlons()` resulting values?  I can submit a concept, if you like.

**Comment by jswhit** [comment]
sure, we could just test latlon values instead.  I though this would be cooler though :-) 

and serve as a set of examples for users

**Comment by akrherz** [comment]
> and serve as a set of examples for users

That would be nice, but maintaining tests for cartopy/matplotlib is super painful, the political line work on the maps is very brittle between various versions.  You have to jump through lots of hoops and baseline image churn, see cartopy and metpy's test suite for example.  I will submit some concepts later this evening.

**Comment by jswhit** [comment]
got the tests to all pass by disabling coastlines and gridlines for those failing tests.  You may be right that this is too fragile, we'll see

**Pull request merged**
