### PR TITLE
add pytest for latlons of two sampledata files

### PR DESCRIPTION
**Pull request by akrherz**
I don't actually have this tied into the testing phase as I don't want to collide with your other PR.

### CODE REVIEW

**Comment by jswhit** [comment]
I think we would need to check more than one point, especially if that point is at the corner of the grid.  The grib metadata often specifies the projection parameters and the grid corners, and we need to test whether the rest of the grid is created correctly.  How about saving the entire lats and lons arrays in a netcdf file or cPickle? Or check two or three points in the grid...

**Comment by akrherz** [comment]
> we need to test whether the rest of the grid is created correctly. How about saving the entire lats and lons arrays in a netcdf file or cPickle

It is at your discretion, that seems like a big hammer for this issue :)  How about testing the four corners and then doing a simple numpy grid operation like mean over all values and testing that result?

**Comment by jswhit** [comment]
It's just that I've seen a lot of very subtle ways the grid locations can get messed up. I guess the four corners plus a randomly chosen point in the interior of the grid ought to be sufficient though.

**Comment by jswhit** [comment]
@akrherz this looks great.  I can go ahead and merge this and we can add other grids to the test in future PRs?

**Comment by akrherz** [comment]
> we can add other grids to the test in future PRs?

Indeed, that was my intention with this, show an example of pytext fixtures and parameterize.  I am also investigating adding a coverage report for this repo, but will handle in later PR.

**Pull request merged**
