### PR TITLE
Update MANIFEST.in

### PR DESCRIPTION
**Pull request by jdkloe**
Added conftest.py to the manifest file. since the tests/test_latlons.py test depends on it. Also remove test.py since it is no longer there.

### CODE REVIEW

**Comment by jdkloe** [comment]
Because conftest.py is not in the manifest it is not included in release 2.1.2 and therefore the latlons test cannot be executed when building the pypi version of pygrib. Therefore I suggest to add it for the next release.

**Comment by jswhit** [comment]
fixed now, thanks.  Will create a new release soon.

**Comment by jdkloe** [comment]
Thanks a lot for accepting my pull request and doing this new 2.1.3 release. This allowed me to activate the cartopy based set of tests in the fedora spec file. I have 2 remaining remarks:

1) I have to perform the tests outside the source directory on my system. If I do it in place then conftest.py file tries to import the $SOURCE/pygrib subdirectory in stead of the one below build/lib.linux-x86_64-3/ even if I let PYTHONPATH point to the proper location. Maybe you can add this suggestion to the documentation, or otherwise this is just a reference for others who might stumble upon the same issue. This build and test sequence works for me:
```tar xvfz pygrib-2.1.3.tar.gz
cd pygrib-2.1.3
python3 setup.py build
export PYTHONPATH=`pwd`/build/lib.linux-x86_64-3.8/
export TESTROOT=`pwd`_tmp_test
mkdir $TESTROOT
cp conftest.py $TESTROOT
cp -R sampledata $TESTROOT
cp -R test $TESTROOT
cd  $TESTROOT/test

python3 -c "import pygrib"
python3 test.py

export MPLBACKEND=agg
python run_tests.py

# note: pyspharm is not yet available in fedora
#       this test is automatically skipped when run as python script
#       but pytest crashes on it so this is just a reminder for now.
python3 test_spectral.py

# this gives 1 error for the test_spectral.py test file:
# pytest test*.py

# this works fine now
pytest test_gaussian.py test_latlons.py \
          test_lambert.py test_ndfd_conus.py \
          test_ndfd_pr.py test_reduced_gg.py \
          test_reduced_ll.py test_reglatlon.py \
          test_rotated_ll.py test_set_bitmap.py  test_stere.py \
           --mpl --mpl-baseline-path=`pwd`/baseline_images
```
2) The pytest test sequence runs fine but it gives me 2 deprecation warnings:
```============================= test session starts ==============================
platform linux -- Python 3.9.1, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
Matplotlib: 3.3.3
Freetype: 2.10.4
rootdir: /builddir/build/BUILD/pygrib-2.1.3-tmp-test/test
plugins: mpl-0.12
collected 29 items
test_gaussian.py .                                                       [  3%]
test_latlons.py ................                                         [ 58%]
test_lambert.py .                                                        [ 62%]
test_ndfd_conus.py .                                                     [ 65%]
test_ndfd_pr.py .                                                        [ 68%]
test_reduced_gg.py .                                                     [ 72%]
test_reduced_ll.py .                                                     [ 75%]
test_reglatlon.py ...                                                    [ 86%]
test_rotated_ll.py .                                                     [ 89%]
test_set_bitmap.py .                                                     [ 93%]
test_stere.py ..                                                         [100%]
=============================== warnings summary ===============================
test_reduced_gg.py::test_reduced_gg
  /usr/lib64/python3.9/site-packages/cartopy/mpl/gridliner.py:307: UserWarning: The .xlabels_top attribute is deprecated. Please use .top_labels to toggle visibility instead.
    warnings.warn('The .xlabels_top attribute is deprecated. Please '
test_reduced_gg.py::test_reduced_gg
  /usr/lib64/python3.9/site-packages/cartopy/mpl/gridliner.py:343: UserWarning: The .ylabels_right attribute is deprecated. Please use .right_labels to toggle visibility instead.
    warnings.warn('The .ylabels_right attribute is deprecated. Please '
-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================= 29 passed, 2 warnings in 11.32s ========================
```
So maybe something to keep in mind for a future version.
For reference, these are the software versions used for the above testing:
gcc 11.0.0
eccodes 2.19.1
python 3.9.1
numpy 1.19.4
cython 0.29.21
pyproj 3.0.0.post1
python3-setuptools 50.3.2
pytest 6.0.2
pytest-mpl 0.12
matplotlib 3.3.3
cartopy 0.18.0
scipy 1.5.4

**Comment by jswhit** [comment]
Thanks for testing!  PR #173 should fix the remaining issues you point out.

**Pull request closed without merging**
