### PR TITLE
DRT 7.4, fixed few bugs with compillation

### PR DESCRIPTION
**Pull request by rkouznetsov**

### CODE REVIEW

**Comment by jswhit** [comment]
This is really a bug in the NCEP g2clib.  Have you reported it to them?

**Comment by rkouznetsov** [comment]
No. I have not figured out wehre to report it.... (did not do much
effort though)

**Comment by jswhit** [comment]
OK, I actually don't know either.  I see no reason not to merge this, but first - why the mods to setup.cfg.template?

**Comment by rkouznetsov** [comment]
Sorry. My first experience with git. Not needed really... How to exclue these mods?

**Comment by jswhit** [comment]
just restore the unmodified version to your branch

**Comment by rkouznetsov** [comment]
Done

**Comment by rkouznetsov** [comment]
One more thing.. Can pygrib.c and g2clib.c files be removed from repo, and their generation introduced to setup.py? That would make the whole thing more consistent...

**Comment by jswhit** [comment]
What's the status of this?  Any luck getting NCEP to include this upstream in g2clib? 

If not, I'm OK with merging.  I just wonder whether re-defining g2int to int32 will cause any problems.

**Comment by jswhit** [comment]
Removing g2clib.c and pygrib.c from the repo would introduce an additional dependency on cython - which I'm reluctant to do.

**Comment by jswhit** [comment]
I checked out your fork and trying to build it, and the build failed because endian.h is missing (it's used by ieeepack.c and ieeeunpack.c).

**Comment by rkouznetsov** [comment]
To me  /usr/include/endian.h came as a part of libc6-dev package.
This seems to be the right way to handle endian in Ubuntu (though, not
in POSIX in general).

Basically, htobeXX  should  be replaced with some portable thing tat converts
native-to-big endian; and   beXXtoh to the opposite one (or same)...

What is the portable way of doing this in pygrib?

**Comment by jswhit** [comment]
some ideas here

http://stackoverflow.com/questions/2100331/c-macro-definition-to-determine-big-endian-or-little-endian-machine

**Comment by hhsprings** [comment]
I'll vote the impl without endian.h, also because for MSVC9, and...

In my [https://github.com/jswhit/pygrib/pull/18](#PR), I didn't fix inttypes.h problem (with old compiler like MSVC9) because this PR11 change typedef int32_t. I think g2clib.pyx should be fixed by using cimport stdint is better than using inttypes.h directly:
```cython
# get 32 bit integer type
from libc.stdint cimport *
```
 
And, I think it would be nice to  mension an available inttypes.h like [https://github.com/chemeris/msinttypes] in somewhere.

**Pull request closed without merging**
